// packages/test-dialogic-react/src/cypress-tests/helpers/buttons.tsx
import React from 'react';

import { DialogicTests } from '../../..';

type ButtonsProps<T> = {
  showFn: DialogicTests.showFn<T>;
  hideFn: DialogicTests.hideFn<T>;
  name?: string;
  id?: string;
  spawn?: string;
};

export const Buttons = <T,>(props: ButtonsProps<T>) => {
  const genName =
    props.name ||
    `${props.id ? `id${props.id}` : ''}${
      props.spawn ? `spawn${props.spawn}` : ''
    }` ||
    'default';

  return (
    <div className="buttons">
      {props.showFn && (
        <button
          type="button"
          className="button primary"
          onClick={props.showFn}
          data-test-id={`button-show-${genName}`}
        >
          {`Show ${genName}`}
        </button>
      )}
      {props.hideFn && (
        <button
          type="button"
          className="button"
          onClick={props.hideFn}
          data-test-id={`button-hide-${genName}`}
        >
          {`Hide ${genName}`}
        </button>
      )}
    </div>
  );
};

// packages/test-dialogic-svelte/src/cypress-tests/Buttons.svelte
<script>
export let showFn;
export let hideFn;
export let id = "";
export let spawn = "";
export let name = "";

const genName = name || `${id ? `id${id}` : ''}${spawn ? `spawn${spawn}` : ''}` || "default";
</script>

<div class="buttons">
{#if showFn}
  <button
    class="button primary"
    on:click={showFn}
    data-test-id={`button-show-${genName}`}
  >
    {`Show ${genName}`}
  </button>
{/if}
{#if hideFn}
  <button
    class="button"
    on:click={hideFn}
    data-test-id={`button-hide-${genName}`}
  >
    {`Hide ${genName}`}
  </button>
{/if}
</div>
