// packages/dialogic-react/src/Dialogical.tsx
import React, { FunctionComponent, useEffect } from 'react';
import { Dialogic } from 'dialogic';
import { Wrapper } from './Wrapper';
import { useDialogicState } from './useDialogicState';

type DialogicalFn = (
  type: Dialogic.DialogicInstance,
) => FunctionComponent<Dialogic.ComponentOptions>;

export const Dialogical: DialogicalFn = instance => props => {
  useDialogicState();

  const identityOptions = {
    id: props.id || instance.defaultId,
    spawn: props.spawn || instance.defaultSpawn,
  };

  // Mount
  useEffect(() => {
    if (typeof props.onMount === 'function') {
      props.onMount();
    }
  }, []);

  return <Wrapper identityOptions={identityOptions} ns={instance.ns} />;
};

// packages/dialogic-svelte-ts/src/Dialogical.svelte
<script lang="ts">
  import type { Dialogic } from "dialogic";

  import { onMount as svelteOnMount } from "svelte";
  import Wrapper from "./Wrapper.svelte";

  export let instance: Dialogic.DialogicInstance;
  export let ns: string = instance.ns;
  export let spawn: string | undefined = undefined;
  export let id: string | undefined = undefined;
  export let onMount: ((args?: unknown) => unknown) | undefined = undefined;

  const identityOptions = {
    id: id || instance.defaultId,
    spawn: spawn || instance.defaultSpawn,
  };

  svelteOnMount(() => {
    if (typeof onMount === "function") {
      onMount();
    }
  });
</script>

<Wrapper {identityOptions} {ns} />
