// packages/demo-dialogic-react-router/src/ProfilePage.tsx
import React, { useState } from 'react';
import { CurrentPathBadge } from './CurrentPathBadge';
import {
  // Route,
  Link,
  useRouteMatch,
  useHistory,
} from 'react-router-dom';
import {
  EditProfileDialog,
  TEditProfileDialogProps,
} from './EditProfileDialog';
import {
  notification,
  // UseDialog,
  useDialog,
} from 'dialogic-react';
import { saveConfirmationProps, TSaveConfirmation } from './SaveConfirmation';

type TProps = {
  pathPrefix?: string;
};

export const ProfilePage = ({ pathPrefix = '' }: TProps) => {
  const [count, setCount] = useState(0);
  const match = useRouteMatch();
  const history = useHistory();
  const dialogPath = `${match.url}/edit`;
  const dialogReturnPath = match.url;
  const matchDialogPath = useRouteMatch(dialogPath);

  useDialog<TEditProfileDialogProps>({
    isShow: matchDialogPath ? matchDialogPath.isExact : false,
    deps: [count],
    props: {
      dialogic: {
        component: EditProfileDialog,
        className: 'dialog',
      },
      pathPrefix,
      title: `Update your e-mail ${count}`,
      email: 'allan@company.com',
      onSave: (email: string) => {
        console.log('onSave:', email);
        history.push(dialogReturnPath);
        notification.show<TSaveConfirmation>(saveConfirmationProps);
      },
      onCancel: () => {
        console.log('onCancel');
        history.push(dialogReturnPath);
      },
      setCount,
    },
  });

  return (
    <div data-test-id="profile-page">
      <h1 className="title">Profile</h1>
      <CurrentPathBadge />
      <div className="buttons">
        <Link className="button" to={pathPrefix || '/'} data-test-id="btn-home">
          Go to Home
        </Link>
        <Link
          className="button is-link"
          to={dialogPath}
          data-test-id="btn-edit-profile"
        >
          Edit Profile
        </Link>
      </div>
      {/* <Route path={dialogPath}>
        <UseDialog<TEditProfileDialogProps>
          isShow={matchDialogPath ? matchDialogPath.isExact : false}
          beforeHide={() => console.log('before hide')}
          props={{
            dialogic: {
              component: EditProfileDialog,
              className: 'dialog',
            },
            title: 'Update your e-mail',
            email: 'allan@company.com',
            onSave: (email: string) => {
              console.log('onSave:', email);
              history.push(dialogReturnPath);
              notification.show<TSaveConfirmation>(saveConfirmationProps);
            },
            onCancel: () => {
              console.log('onCancel');
              history.push(dialogReturnPath);
            },
          }}
        />
      </Route> */}
    </div>
  );
};

// packages/demo-dialogic-svelte-router/src/ProfilePage.svelte
<script>
  import CurrentPathBadge from './CurrentPathBadge.svelte';
  import EditProfileDialog from './EditProfileDialog.svelte';
  import { UseDialog, notification } from 'dialogic-svelte';
  import { link } from 'svelte-spa-router';
  import { location, push } from 'svelte-spa-router';
  import { email, counter, increment } from './store';
  import SaveConfirmation, {
    createSaveConfirmationProps,
  } from './SaveConfirmation.svelte';

  /* Location */
  const dialogPath = '/profile/edit';
  const dialogReturnPath = '/profile';
  $: isMatchDialogPath = $location === dialogPath;

  // UseDialog props
  // Make props reactive so that the title gets updated with changes to counter
  $: useDialogProps = {
    dialogic: {
      component: EditProfileDialog,
      className: 'dialog',
    },
    title: `Update your e-mail ${$counter}`,
    email: $email,
    onSave: newEmail => {
      if (newEmail !== $email) {
        email.set(newEmail);
        notification.show(createSaveConfirmationProps(SaveConfirmation));
      }
      push(dialogReturnPath);
    },
    onCancel: () => {
      push(dialogReturnPath); // we could also pass dialogReturnPath to the dialog to use it as a link href
    },
    increment,
  };
</script>

<div data-test-id="profile-page">
  <h1 class="title">Profile</h1>
  <CurrentPathBadge />

  <div class="profile-tile">
    <div><strong>Email</strong></div>
    <div data-test-id="current-email">{$email}</div>
    <a
      class="button is-link"
      href={dialogPath}
      use:link
      data-test-id="btn-edit-profile">
      Edit
    </a>
  </div>

  <div class="buttons">
    <a
      class="button is-link is-light is-outlined"
      href={'/'}
      use:link
      data-test-id="btn-home">
      Go to Home
    </a>
  </div>
  <UseDialog
    props={useDialogProps}
    isShow={isMatchDialogPath}
    deps={[$counter]} />
</div>
