// packages/demo-dialogic-svelte/src/RemainingLabel.svelte
<script>
  import { remaining } from "dialogic";

  export let instance;
  export let roundToSeconds;
  let remainingSeconds;

  remaining({
    instance,
    roundToSeconds: roundToSeconds,
    callback: (newValue) => {
      remainingSeconds = newValue;
    },
  });
  
</script>

<div class="remaining">
  <span>
    {remainingSeconds === undefined
      ? "0"
      : remainingSeconds.toString()
    }
  </span>
</div>

<style>
.remaining {
  min-width: 3em;
  text-align: left;
}
</style>

// packages/demo-dialogic-react/src/RemainingLabel.tsx
import React from 'react';
import { notification, useRemaining } from 'dialogic-react';

export const RemainingLabel = () => {
  const [remainingSeconds] = useRemaining({
    instance: notification,
    roundToSeconds: false,
  });

  return (
    <span
      style={{
        minWidth: '3em',
        textAlign: 'left',
      }}
    >
      {remainingSeconds === undefined ? '0' : remainingSeconds.toString()}
    </span>
  );
};
