// packages/test-dialogic-svelte/src/cypress-tests/DialogQueued.svelte
<script>
  import { Dialog, dialog } from "dialogic-svelte";
  import Default from "./content/Default.svelte";
  import Buttons from "./Buttons.svelte";
  import { createFns } from "./createFns.ts";

  dialog.resetAll()
  const fns = createFns({ instance: dialog, component: Default, className: "dialog", title: "Default", queued: true });
  const dialogCount = dialog.getCount();
</script>

<div class="test">
  <div class="control" data-test-id="count-all">{`Count all: ${$dialogCount}`}</div>
  <div class="content">
    <Buttons {...fns} />
  </div>
  <div class="spawn default-spawn">
    <Dialog />
  </div>
</div>

// packages/test-dialogic-react/src/cypress-tests/DialogQueued.tsx
import React, { useEffect } from 'react';
import { createFns } from './createFns';
import { Default } from '../content/Default';
import { Buttons } from './Buttons';
import { dialog, Dialog, useDialogicState } from 'dialogic-react';

export default () => {
  useEffect(() => {
    dialog.resetAll();
  }, []);
  useDialogicState();
  const fns = createFns({
    instance: dialog,
    component: Default,
    className: 'dialog',
    title: 'Default',
    queued: true,
  });

  return (
    <div className="test">
      <div
        className="control"
        data-test-id="count-all"
      >{`Count all: ${dialog.getCount()}`}</div>
      <div className="content">
        <Buttons {...fns} />
      </div>
      <div className="spawn default-spawn">
        <Dialog />
      </div>
    </div>
  );
};
