// packages/test-dialogic-svelte/src/cypress-tests/DialogClassNameDelay.svelte
<script>
  import { Dialog, dialog } from "dialogic-svelte";
  import Default from "./content/Default.svelte";
  import Buttons from "./Buttons.svelte";
  import { createFns } from "./createFns";

  const fns = createFns({ instance: dialog, component: Default, className: "dialog-delay", title: "DialogClassDelay" });
</script>

<div class="test">
  <Buttons {...fns} />
  <div class="spawn default-spawn">
    <Dialog />
  </div>
</div>

// packages/test-dialogic-react/src/cypress-tests/DialogClassNameDelay.tsx
import React from "react";
import { createFns } from "./createFns";
import { Default } from "../content/Default";
import { buttons } from "./buttons";
import { dialog, Dialog } from "dialogic-react";

export default () => {
  const fns = createFns({ instance: dialog, component: Default, className: "dialog-delay", title: "DialogClassDelay" });

  return (
    <div className="test">
      {buttons(fns)}
      <div className="spawn default-spawn">
        <Dialog />
      </div>
    </div> 
  );
};
