// packages/test-dialogic-svelte/src/cypress-tests/DialogTimeout.svelte
<script>
  import { Dialog, dialog } from "dialogic-svelte";
  import Default from "./content/Default.svelte";
  import Buttons from "./Buttons.svelte";
  import Remaining from "./Remaining.svelte";
  import { createFns } from "./createFns.ts";

  dialog.resetAll();
  const fns = createFns({ instance: dialog, component: Default, className: "dialog", title: "Default", timeout: 2000 });
  const dialogIsPaused = dialog.isPaused();
</script>

<div class="test">
  <div class="control" data-test-id="reset-all">
    <div class="buttons">
      <button class="button" data-test-id="button-pause" on:click={() => dialog.pause()}>
        Pause
      </button>
      <button class="button" data-test-id="button-resume" on:click={() => dialog.resume()}>
        Resume
      </button>
      <button class="button" data-test-id="button-reset" on:click={() => dialog.resetAll()}>
        Reset
      </button>
    </div>
  </div>
  <div class="control" data-test-id="is-paused">
    {`Is paused: ${$dialogIsPaused}`}
  </div>
  <div class="control">
    <Remaining getRemainingFn={dialog.getRemaining} />
  </div>
  <div class="content">
    <Buttons {...fns} />
  </div>
  <div class="spawn default-spawn">
    <Dialog />
  </div>
</div>

// packages/test-dialogic-react/src/cypress-tests/DialogTimeout.tsx
import React, { useEffect } from "react";
import { createFns } from "./createFns";
import { Default } from "../content/Default";
import { buttons } from "./buttons";
import { dialog, Dialog, useDialogicState } from "dialogic-react";
import { Remaining } from "./Remaining";

export default () => {
  useEffect(
    () => {
      dialog.resetAll();
    },
    []
  );

  useDialogicState();
  const fns = createFns({ instance: dialog, component: Default, className: "dialog", title: "Default", timeout: 2000 });

  return (
    <div className="test">
      <div className="control" data-test-id="reset-all">
        <div className="buttons">
          <button className="button" data-test-id="button-pause" onClick={() => dialog.pause()}>
            Pause
          </button>
          <button className="button" data-test-id="button-resume" onClick={() => dialog.resume()}>
            Resume
          </button>
          <button className="button" data-test-id="button-reset" onClick={() => dialog.resetAll()}>
            Reset
          </button>
        </div>
      </div>
      <div className="control" data-test-id="is-paused">
        {`Is paused: ${dialog.isPaused()}`}
      </div>
      <div className="control">
        <Remaining getRemainingFn={dialog.getRemaining} />
      </div>
      <div className="content">
        {buttons({ ...fns })}
      </div>
      <div className="spawn default-spawn">
        <Dialog />
      </div>
    </div> 
  );
};
