// packages/test-dialogic-svelte/src/cypress-tests/Remaining.svelte
<script>
	import { onDestroy } from "svelte";

	export let getRemainingFn;
	
	let displayValue = 0;
	let reqId;
	
  const update = () => {
    const value = getRemainingFn();
    displayValue = value === undefined
      ? undefined
      : Math.max(value, 0);
    reqId = window.requestAnimationFrame(update);
  };
	reqId = window.requestAnimationFrame(update);
	
	onDestroy(() => {
		window.cancelAnimationFrame(reqId);
  });
  
</script>

<div data-test-id="remaining">
  <span>Remaining: </span>
  <span data-test-id="remaining-value">{displayValue === undefined
    ? "undefined"
    : displayValue.toString()}</span>
</div>

// packages/test-dialogic-react/src/cypress-tests/Remaining.tsx
import React, { useState, FunctionComponent } from "react";
import { useAnimationFrame } from "./useAnimationFrame";

type RemainingProps = {
  getRemainingFn: () => number | undefined;
}

export const Remaining: FunctionComponent<RemainingProps> = props => {
  const [displayValue, setDisplayValue] = useState();

  useAnimationFrame(() => {
    const remaining = props.getRemainingFn();
    if (remaining !== undefined && displayValue !== remaining) {
      setDisplayValue(Math.max(remaining, 0));
    } else {
      setDisplayValue(undefined);
    }
  });

  return (
    <div data-test-id="remaining">
      <span>Remaining: </span>
      <span data-test-id="remaining-value">{displayValue === undefined
        ? "undefined"
        : displayValue.toString()}</span>
    </div>
  );

};
