// packages/dialogic-svelte/src/Instance.svelte
<script>
  import { onMount, createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  // DOM bindings
  let domElement;

  export let identityOptions = undefined;
  export let passThroughOptions = undefined;
  export let dialogicOptions = undefined;

  const className = dialogicOptions.className;

  const dispatchTransition = (name) =>
    dispatch(name, {
      identityOptions,
      domElement
    });

  const show = () => {
    dispatchTransition("show");
  };

  const hide = () => {
    dispatchTransition("hide");
  };

  onMount(() => {
    dispatchTransition("mount");
  });

</script>

<div 
  class={className}
  bind:this={domElement}
>
  <svelte:component this={dialogicOptions.component} {show} {hide} {...passThroughOptions} />
</div>

// packages/dialogic-react/src/Instance.tsx

import React, { FunctionComponent, useCallback, useRef } from "react";
import { Dialogic } from "dialogic";

interface Instance extends Dialogic.DialogicalInstanceOptions{}

export const Instance: FunctionComponent<Dialogic.DialogicalInstanceOptions> = props => {
  const domElementRef = useRef();
  const className = props.dialogicOptions.className;
  const Component = props.dialogicOptions.component;

  const domElementCb = useCallback(node => {
    if (node !== null) {
      domElementRef.current = node;
      onMount();
    }
  }, []);

  const dispatchTransition = (dispatchFn: Dialogic.DialogicalInstanceDispatchFn) => {    
    const domElement = domElementRef.current;
    if (domElement === undefined) {
      return;
    }
    dispatchFn({
      detail: {
        identityOptions: props.identityOptions,
        domElement
      }
    });
  };

  const onMount = () => {
    dispatchTransition(props.onMount);
  };

  const show = () => {
    dispatchTransition(props.onShow);
  };

  const hide = () => {
    dispatchTransition(props.onHide);
  };

  return (
    <div
      ref={domElementCb}
      className={className}
    >
      <Component
        {...props.passThroughOptions}
        show={show}
        hide={hide}
      />
    </div>
  );
};
