// packages/dialogic-svelte-ts/src/Wrapper.svelte
<script>
  import { appState } from "./store";
  import { filterCandidates } from "dialogic";
  import {
    onInstanceMounted,
    onShowInstance,
    onHideInstance,
  } from "./instanceEvents";
  import Instance from "./Instance.svelte";

  export let identityOptions;
  export let ns;

  const nsOnInstanceMounted = onInstanceMounted(ns);
  const nsOnShowInstance = onShowInstance(ns);
  const nsOnHideInstance = onHideInstance(ns);
</script>

{#each filterCandidates(ns, $appState.store, identityOptions) as { identityOptions, dialogicOptions, passThroughOptions, key }, index (key)}
  <Instance
    {identityOptions}
    {dialogicOptions}
    {passThroughOptions}
    on:mount={nsOnInstanceMounted}
    on:show={nsOnShowInstance}
    on:hide={nsOnHideInstance}
  />
{/each}

// packages/dialogic-react/src/Wrapper.tsx
import { Dialogic, filterCandidates, selectors } from "dialogic";
import React from "react";
import { Instance } from "./Instance";
import {
  onHideInstance,
  onInstanceMounted,
  onShowInstance,
} from "./instanceEvents";

export const Wrapper = (props: Dialogic.DialogicalWrapperOptions) => {
  const nsOnInstanceMounted = onInstanceMounted(props.ns);
  const nsOnShowInstance = onShowInstance(props.ns);
  const nsOnHideInstance = onHideInstance(props.ns);

  const identityOptions: Dialogic.IdentityOptions =
    props.identityOptions || ({} as Dialogic.IdentityOptions);
  const filtered = filterCandidates(
    props.ns,
    selectors.getStore(),
    identityOptions
  );

  return (
    <>
      {filtered.map((item) => (
        <Instance
          key={item.key}
          identityOptions={item.identityOptions}
          dialogicOptions={
            item.dialogicOptions as Dialogic.DialogicOptions<Dialogic.PassThroughOptions>
          }
          passThroughOptions={
            item.passThroughOptions as Dialogic.PassThroughOptions
          }
          onMount={nsOnInstanceMounted}
          onShow={nsOnShowInstance}
          onHide={nsOnHideInstance}
        />
      ))}
    </>
  );
};
