// packages/demo-dialogic-svelte-router/src/ProfilePage.svelte
<script>
  import CurrentPathBadge from './CurrentPathBadge.svelte';
  import EditProfileDialog from './EditProfileDialog.svelte';
  import { UseDialog, notification } from 'dialogic-svelte';
  import { link } from 'svelte-spa-router';
  import { location, push } from 'svelte-spa-router';
  import { email, counter, increment } from './store';
  import SaveConfirmation, {
    createSaveConfirmationProps,
  } from './SaveConfirmation.svelte';

  /* Location */
  const dialogPath = '/profile/edit';
  const dialogReturnPath = '/profile';
  $: isMatchDialogPath = $location === dialogPath;

  // UseDialog props
  // Make props reactive so that the title gets updated with changes to counter
  $: useDialogProps = {
    dialogic: {
      component: EditProfileDialog,
      className: 'dialog',
    },
    title: `Update your e-mail ${$counter}`,
    email: $email,
    onSave: newEmail => {
      if (newEmail !== $email) {
        email.set(newEmail);
        notification.show(createSaveConfirmationProps(SaveConfirmation));
      }
      push(dialogReturnPath);
    },
    onCancel: () => {
      push(dialogReturnPath); // we could also pass dialogReturnPath to the dialog to use it as a link href
    },
    increment,
  };
</script>

<div data-test-id="profile-page">
  <h1 class="title">Profile</h1>
  <CurrentPathBadge />

  <div class="profile-tile">
    <div><strong>Email</strong></div>
    <div data-test-id="current-email">{$email}</div>
    <a
      class="button is-link"
      href={dialogPath}
      use:link
      data-test-id="btn-edit-profile">
      Edit
    </a>
  </div>

  <div class="buttons">
    <a
      class="button is-link is-light is-outlined"
      href={'/'}
      use:link
      data-test-id="btn-home">
      Go to Home
    </a>
  </div>
  <UseDialog
    props={useDialogProps}
    isShow={isMatchDialogPath}
    deps={[$counter]} />
</div>

// packages/demo-dialogic-react-router/src/pages/ProfilePage.tsx
import { notification, UseDialog, useDialog } from "dialogic-react";
import React from "react";
import { Link, Route, useHistory, useRouteMatch } from "react-router-dom";
import { CurrentPathBadge } from "../components/CurrentPathBadge";
import {
  EditProfileDialog,
  EditProfileDialogProps,
} from "../components/EditProfileDialog";
import {
  saveConfirmationData,
  SaveConfirmationProps,
} from "../components/SaveConfirmation";
import { TStore } from "../store";

type Props = {
  /**
   * Used for e2e tests.
   */
  pathPrefix?: string;
  useDialogComponent?: boolean;
  store: TStore;
};

export const ProfilePage = ({
  pathPrefix = "",
  useDialogComponent,
  store,
}: Props) => {
  // Test injecting a dynamic value into the dialog

  const match = useRouteMatch();
  const history = useHistory();
  const dialogPath = `${match.url}/edit`;
  const dialogReturnPath = match.url;
  const matchDialogPath = useRouteMatch(dialogPath);

  const useDialogProps = {
    dialogic: {
      component: EditProfileDialog,
      className: "dialog",
    },
    pathPrefix,
    title: `Update your e-mail ${store.count}`,
    email: store.email,
    onSave: (newEmail: string) => {
      if (newEmail !== store.email) {
        store.setEmail(newEmail);
        notification.show<SaveConfirmationProps>(saveConfirmationData);
      }
      history.push(dialogReturnPath);
    },
    onCancel: () => {
      history.push(dialogReturnPath); // we could also pass dialogReturnPath to the dialog to use it as Link `to`
    },
    increment: store.increment,
  };

  useDialog<EditProfileDialogProps>({
    isIgnore: useDialogComponent,
    isShow: matchDialogPath ? matchDialogPath.isExact : false,
    deps: [store.count], // update the dialog contents whenever count changes
    props: useDialogProps,
  });

  return (
    <div data-test-id="profile-page">
      <h1 className="title">Profile</h1>
      <CurrentPathBadge />
      <div className="profile-tile">
        <div>
          <strong>Email</strong>
        </div>
        <div data-test-id="current-email">{store.email}</div>
        <Link
          className="button is-link"
          to={dialogPath}
          data-test-id="btn-edit-profile"
        >
          Edit
        </Link>
      </div>

      <div className="buttons">
        <Link
          className="button is-link is-light is-outlined"
          to={pathPrefix || "/"}
          data-test-id="btn-home"
        >
          Go to Home
        </Link>
      </div>
      {useDialogComponent && (
        <Route path={dialogPath}>
          <UseDialog<EditProfileDialogProps>
            isShow={matchDialogPath ? matchDialogPath.isExact : false}
            deps={[store.count]}
            props={useDialogProps}
          />
        </Route>
      )}
    </div>
  );
};
