// packages/demo-dialogic-svelte/src/Remaining.svelte
<script>
	import { onDestroy } from "svelte";

	export let getRemaining;
	
	let displayValue = 0;
	let reqId;
	
  const update = () => {
    const value = getRemaining();
    displayValue = value === undefined
      ? undefined
      : Math.max(value, 0);
    reqId = window.requestAnimationFrame(update);
  };
	reqId = window.requestAnimationFrame(update);
	
	onDestroy(() => {
		window.cancelAnimationFrame(reqId);
  });
  
</script>

<div data-test-id="remaining">
  <span data-test-id="remaining-value">{displayValue === undefined
    ? "undefined"
    : displayValue.toString()}</span>
</div>

// packages/demo-react/src/Remaining.tsx
import React, { FunctionComponent, useState, useEffect, useRef } from "react";

type RemainingProps = {
  getRemaining: () => number | undefined;
}

export const Remaining: FunctionComponent<RemainingProps> = props => {
  const [displayValue, setDisplayValue] = useState();
  const reqRef = useRef<number>(0);

  const update = () => {
    const remaining = props.getRemaining();
    if (remaining !== undefined) {
      if (displayValue !== remaining) {
        setDisplayValue(Math.max(remaining, 0));
      }
    } else {
      setDisplayValue(undefined);
    }
    // Loop:
    reqRef.current = window.requestAnimationFrame(update);
  };

  useEffect(
    () => {
      reqRef.current = window.requestAnimationFrame(update);

      return () => {
        window.cancelAnimationFrame(reqRef.current);
      }
    },
    []
  );

  return (
    <div>{`Remaining: ${displayValue}`}</div>
  );
};
