// packages/demo-svelte/src/remaining/Remaining.svelte
<script>
	import { onDestroy } from "svelte";

	export let getRemainingFn;
	
	let displayValue = 0;
	let reqId;
	
  const update = () => {
    const value = getRemainingFn();
    displayValue = value === undefined
      ? undefined
      : Math.max(value, 0);
    reqId = window.requestAnimationFrame(update);
  };
	reqId = window.requestAnimationFrame(update);
	
	onDestroy(() => {
		window.cancelAnimationFrame(reqId);
	});
</script>

<div>
  Remaining: {displayValue}
</div>

// packages/demo-react/src/Remaining.tsx
import React, { FunctionComponent, useState, useEffect, useRef } from "react";

type RemainingProps = {
  getRemaining: () => number | undefined;
}

export const Remaining: FunctionComponent<RemainingProps> = props => {
  const [displayValue, setDisplayValue] = useState();
  const reqRef = useRef<number>(0);

  const update = () => {
    const remaining = props.getRemaining();
    if (remaining !== undefined) {
      if (displayValue !== remaining) {
        setDisplayValue(Math.max(remaining, 0));
      }
    } else {
      setDisplayValue(undefined);
    }
    // Loop:
    reqRef.current = window.requestAnimationFrame(update);
  };

  useEffect(
    () => {
      reqRef.current = window.requestAnimationFrame(update);

      return () => {
        window.cancelAnimationFrame(reqRef.current);
      }
    },
    []
  );

  return (
    <div>{`Remaining: ${displayValue}`}</div>
  );
};
