// packages/demo-dialogic-svelte-router/src/EditProfileDialog.svelte
<script>
  import { link } from 'svelte-spa-router';

  export let title;
  export let email;
  export let onSave;
  export let onCancel;
  export let increment;

  let newEmail = email;
</script>

<div class="modal is-active" data-test-id="edit-profile-dialog">
  <div class="modal-background" />
  <form class="modal-card" on:submit={() => onSave(newEmail)}>
    <header class="modal-card-head">
      <p class="modal-card-title" data-test-id="title">{title}</p>
      <button class="delete" data-test-id="btn-close" on:click={onCancel} />
    </header>
    <section class="modal-card-body">
      <div class="field">
        <div class="control">
          <input
            class="input"
            type="text"
            data-test-id="input-email"
            bind:value={newEmail} />
        </div>
      </div>
    </section>
    <footer class="modal-card-foot">
      <div class="footer-buttons">
        <button
          type="submit"
          class="button is-link"
          data-test-id="btn-save"
          on:click={() => onSave(newEmail)}>
          Save changes
        </button>
        <a
          class="button is-link is-light is-outlined"
          href="/"
          use:link
          data-test-id="btn-home">
          Go to Home
        </a>
        <button
          type="button"
          class="button is-link is-light is-outlined"
          data-test-id="btn-add-count"
          on:click={increment}>
          Dynamic title count
        </button>
        <button
          type="button"
          class="button is-danger is-light is-outlined"
          data-test-id="btn-cancel"
          on:click={onCancel}>
          Cancel
        </button>
      </div>
    </footer>
  </form>
</div>

// packages/demo-dialogic-react-router/src/EditProfileDialog.tsx
import React, { FunctionComponent, useState, FormEvent } from 'react';
import { Link } from 'react-router-dom';

export type TEditProfileDialogProps = {
  email: string;
  title: string;
  pathPrefix?: string;
  onCancel: () => void;
  onSave: (email: string) => void;
  increment: () => void;
};

export const EditProfileDialog: FunctionComponent<TEditProfileDialogProps> = props => {
  const [email, setEmail] = useState(props.email);
  return (
    <div className="modal is-active" data-test-id="edit-profile-dialog">
      <div className="modal-background" />
      <form
        className="modal-card"
        onSubmit={(e: FormEvent) => {
          e.preventDefault();
          props.onSave(email);
        }}
      >
        <header className="modal-card-head">
          <p className="modal-card-title" data-test-id="title">
            {props.title}
          </p>
          <button
            type="button"
            className="delete"
            onClick={() => {
              props.onCancel();
            }}
            data-test-id="btn-close"
          />
        </header>
        <section className="modal-card-body">
          <div className="field">
            <div className="control">
              <input
                className="input"
                type="email"
                defaultValue={email}
                onChange={e => setEmail(e.target.value)}
                data-test-id="input-email"
              />
            </div>
          </div>
        </section>
        <footer className="modal-card-foot">
          <div className="footer-buttons">
            <button
              type="submit"
              className="button is-link"
              data-test-id="btn-save"
            >
              Save changes
            </button>

            <Link
              className="button is-link is-light is-outlined"
              to={props.pathPrefix || '/'}
              data-test-id="btn-home"
            >
              Go to home
            </Link>
            <button
              type="button"
              className="button is-link is-light is-outlined"
              onClick={props.increment}
              data-test-id="btn-add-count"
            >
              Dynamic title count
            </button>
            <button
              type="button"
              className="button is-danger is-light is-outlined"
              onClick={() => props.onCancel()}
              data-test-id="btn-cancel"
            >
              Cancel
            </button>
          </div>
        </footer>
      </form>
    </div>
  );
};
